const SET_CURRENCY = "SET_CURRENCY";
const SET_DATA = "SET_DATA";
const SET_DATA_LOADING = "SET_DATA_LOADING";
const SET_HISTORY_LOADING = "SET_HISTORY_LOADING";
const SET_HISTORY = "SET_HISTORY";
const ADD_COIN = "ADD_COIN";
const REMOVE_COIN = "REMOVE_COIN";
const CHANGE_COIN_AMOUNT = "CHANGE_COIN_AMOUNT";
const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
const SET_PAGE = "SET_PAGE";
const SET_EXPORT_LOADING = "SET_EXPORT_LOADING";
const SET_EXPORT_ERROR = "SET_EXPORT_ERROR";
const SET_EXPORT_CODE = "SET_EXPORT_CODE";
const IMPORT = "IMPORT";
const SET_IMPORT_LOADING = "SET_IMPORT_LOADING";
const SET_IMPORT_SUCCESS = "SET_IMPORT_SUCCESS";
const SET_IMPORT_ERROR = "SET_IMPORT_ERROR";
const SET_CLOUD_CONFLICT = "SET_CLOUD_CONFLICT";
const BUMP_VERSION = "BUMP_VERSION";

export {
  SET_CURRENCY,
  SET_DATA,
  SET_DATA_LOADING,
  SET_HISTORY_LOADING,
  SET_HISTORY,
  ADD_COIN,
  REMOVE_COIN,
  CHANGE_COIN_AMOUNT,
  ADD_TO_WATCHLIST,
  REMOVE_FROM_WATCHLIST,
  SET_PAGE,
  SET_EXPORT_LOADING,
  SET_EXPORT_ERROR,
  SET_EXPORT_CODE,
  IMPORT,
  SET_IMPORT_LOADING,
  SET_IMPORT_SUCCESS,
  SET_IMPORT_ERROR,
  SET_CLOUD_CONFLICT,
  BUMP_VERSION
};
